import Head from "next/head";
import { Banner } from "@/components/banner";
import { LatestCompanyPromotions } from "@/components/latest-company-promotions";
import { AboutUs } from "@/components/about-us";
import { Advantages } from "@/components/advantages";
import s from "./AboutPage.module.scss";
import { FeedbackForm } from "@/components/feedback-form";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>Shares</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.container}>
        <AboutUs />
        <Advantages />
        <Banner />
        <LatestCompanyPromotions />
        <FeedbackForm />
      </div>
    </>
  );
}
