import Head from "next/head";
import { FeedbackForm } from "@/components/feedback-form";
import { BusinessBanner } from "@/components/business-banner";
import { BenefitsOfWorking } from "@/components/benefits-of-working";
import { WorkProcess } from "@/components/work-process";
import { Services } from "@/components/services";

export default function ContactsPage() {
  return (
    <>
      <Head>
        <title>Сотрудничесто</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <BusinessBanner />
        <BenefitsOfWorking />
        <WorkProcess />
        <Services />
        <FeedbackForm />
      </div>
    </>
  );
}
