import Head from "next/head";
import s from "./RegularCustomerPage.module.scss";
import { RegularCustomer } from "@/components/regular-customer";

export default function RegularCustomerPage() {
  return (
    <>
      <Head>
        <title>Постоянный клиент</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.main}>
        <RegularCustomer />
      </div>
    </>
  );
}
