import Head from "next/head";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { FeedbackForm } from "@/components/feedback-form";
import s from "./ContactsPage.module.scss";
import { CompanyContacts } from "@/components/company-contacts";

export default function ContactsPage() {
  return (
    <>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.main}>
        <Header />
        <CompanyContacts variant="secondary" />
        <FeedbackForm />
        <Footer />
      </div>
    </>
  );
}
