import Head from "next/head";
import clsx from "clsx";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { CatalogWithBanners } from "@/components/catalog-with-banners";
import { ProductCatalog } from "@/components/product-catalog";
import { LatestCompanyPromotions } from "@/components/latest-company-promotions";
import { CompanyContacts } from "@/components/company-contacts";
import { Banner } from "@/components/banner";
import { FeedbackForm } from "@/components/feedback-form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <CatalogWithBanners />
        <ProductCatalog />
        <LatestCompanyPromotions />
        <CompanyContacts />
        <Banner />
        <FeedbackForm />
        <Footer />
      </div>
    </>
  );
}
