import Head from "next/head";
import { FeedbackForm } from "@/components/feedback-form";
import { VacancieBanner } from "@/components/vacancie-banner";
import { ReasonsCards } from "@/components/reasons-cards";
import { MastersClub } from "@/components/masters-club";

export default function ContactsPage() {
  return (
    <>
      <Head>
        <title>Сотрудничесто</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <VacancieBanner />
        <ReasonsCards />
        <MastersClub />
        <FeedbackForm />
      </div>
    </>
  );
}
