import { useRouter } from "next/router";
import Head from "next/head";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { FeedbackForm } from "@/components/feedback-form";
import { OtherCompanyShares } from "@/components/other-company-shares";
import { SharesInfo } from "@/components/shares-info";
import s from "./SharesPage.module.scss";

const ShareDetailPage = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>Акции {id}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.container}>
        <Header />
        <SharesInfo />
        <OtherCompanyShares />
        <FeedbackForm />
        <Footer />
      </div>
    </>
  );
};

export default ShareDetailPage;
