import Head from "next/head";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { FeedbackForm } from "@/components/feedback-form";
import { Shares } from "@/components/shares";
import s from "./SharesPage.module.scss";

export default function SharesPage() {
  return (
    <>
      <Head>
        <title>Shares</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.container}>
        <Header />
        <Shares />
        <FeedbackForm />
        <Footer />
      </div>
    </>
  );
}
